# Data Preprocessing

## Importing the libraries

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import r2_score


## Importing the datasets

In [32]:
dataset2013= pd.read_csv('wheat-2013-supervised.csv')
dataset2014 = pd.read_csv('wheat-2014-supervised.csv')

#merging the datas to create a single dataset
dataset = pd.concat([dataset2013, dataset2014],axis=0)

## Understanding the Dataset

In [35]:
print(dataset2013.shape)
print(dataset2014.shape)
print(dataset.shape)


(177493, 26)
(182549, 26)
(360042, 26)


In [36]:
#dataset2013.head()
#dataset2014.head()
dataset.head()

CountyName       State   Latitude   Longitude             Date  \
0      Adams  Washington  46.811686 -118.695237  11/30/2013 0:00   
1      Adams  Washington  46.929839 -118.352109  11/30/2013 0:00   
2      Adams  Washington  47.006888 -118.510160  11/30/2013 0:00   
3      Adams  Washington  47.162342 -118.699677  11/30/2013 0:00   
4      Adams  Washington  47.157512 -118.434056  11/30/2013 0:00   

   apparentTemperatureMax  apparentTemperatureMin  cloudCover  dewPoint  \
0                   35.70                   20.85        0.00     29.53   
1                   35.10                   26.92        0.00     29.77   
2                   33.38                   26.95        0.00     29.36   
3                   28.05                   25.93        0.91     29.47   
4                   28.83                   25.98        0.91     29.86   

   humidity  ...    precipTypeIsOther  pressure  temperatureMax  \
0      0.91  ...                    0   1027.13           35.70   
1      0.93  ...                    0   1026.87           35.10   
2      0.94  ...                    0   1026.88           33.38   
3      0.94  ...                    0   1026.37           33.19   
4      0.94  ...                    0   1026.19           33.85   

   temperatureMin  visibility  windBearing  windSpeed        NDVI  \
0           27.48        2.46          214       1.18  134.110657   
1           26.92        2.83          166       1.01  131.506592   
2           26.95        2.95          158       1.03  131.472946   
3           27.17        2.89          153       1.84  131.288300   
4           27.07        2.97          156       1.85  131.288300   

   DayInSeason  Yield  
0            0   35.7  
1            0   35.7  
2            0   35.7  
3            0   35.7  
4            0   35.7  

[5 rows x 26 columns]

In [37]:
dataset.describe()

Latitude      Longitude  apparentTemperatureMax  \
count  360042.000000  360042.000000           360042.000000   
mean       37.247296    -100.710146               56.007530   
std         4.930159       5.776731               22.101277   
min        27.363741    -120.914093              -39.970000   
25%        33.898188    -101.249768               39.640000   
50%        36.508221     -99.108600               60.230000   
75%        38.761695     -97.309181               73.020000   
max        48.981928     -94.164602              177.320000   

       apparentTemperatureMin     cloudCover       dewPoint       humidity  \
count           360042.000000  360042.000000  360042.000000  360042.000000   
mean                30.832834       0.101798      33.237347       0.637762   
std                 21.053908       0.158358      16.807035       0.162896   
min                -58.420000       0.000000     -36.090000       0.080000   
25%                 17.420000       0.000000      22.300000       0.520000   
50%                 29.930000       0.040000      31.250000       0.640000   
75%                 45.610000       0.140000      44.590000       0.760000   
max                 79.560000       1.000000      78.350000       1.000000   

       precipIntensity  precipIntensityMax  precipProbability      ...        \
count    360041.000000       360041.000000      360041.000000      ...         
mean          0.001839            0.016087           0.170108      ...         
std           0.006100            0.059991           0.284588      ...         
min           0.000000            0.000000           0.000000      ...         
25%           0.000000            0.000000           0.000000      ...         
50%           0.000000            0.000000           0.000000      ...         
75%           0.000500            0.005600           0.250000      ...         
max           0.255800            3.367400           0.970000      ...         

       precipTypeIsOther       pressure  temperatureMax  temperatureMin  \
count           360042.0  359437.000000   360042.000000   360042.000000   
mean                 0.0    1017.940465       58.278807       36.606141   
std                  0.0       8.229700       19.143224       16.928982   
min                  0.0     942.490000      -22.000000      -39.790000   
25%                  0.0    1012.260000       44.720000       25.810000   
50%                  0.0    1017.530000       60.230000       35.930000   
75%                  0.0    1023.390000       73.020000       48.620000   
max                  0.0    1049.530000      105.200000       79.560000   

          visibility    windBearing      windSpeed           NDVI  \
count  359996.000000  360042.000000  360042.000000  360042.000000   
mean        9.162223     181.310244       8.010297     146.112990   
std         1.387730     103.863570       4.448867      10.237413   
min         0.460000       0.000000       0.020000     101.000000   
25%         8.940000     106.000000       4.620000     137.042152   
50%         9.830000     181.000000       7.350000     146.911461   
75%        10.000000     261.000000      10.800000     153.065185   
max        10.000000     359.000000      31.730000     208.000000   

         DayInSeason          Yield  
count  360042.000000  360042.000000  
mean       92.643111      32.656495  
std        53.621134      13.146621  
min         0.000000       9.000000  
25%        46.000000      23.000000  
50%        93.000000      32.000000  
75%       139.000000      42.200000  
max       185.000000      78.000000  

[8 rows x 23 columns]

In [38]:
# Removing Columns which will not contribute to predicting Yield
total_data1 = dataset.drop(['CountyName','State','Latitude','Longitude','Date'],axis=1)

In [39]:
# Deleting the rows which have empty features
total_data2 = total_data1.dropna(axis = 0)

In [40]:
# Yield data
print(total_data2['Yield'])

0         35.7
1         35.7
2         35.7
3         35.7
4         35.7
5         35.7
6         14.4
7         14.4
8         14.4
9         14.4
10        14.4
11        14.4
12        46.5
13        46.5
14        46.5
15        46.5
16        46.5
17        46.5
18        45.6
19        45.6
20        45.6
21        45.6
22        45.6
23        45.6
24        13.1
25        13.1
26        13.1
27        13.1
28        13.1
29        13.1
          ... 
182519    45.8
182520    45.8
182521    45.8
182522    45.8
182523    45.8
182524    45.8
182525    39.3
182526    39.3
182527    39.3
182528    39.3
182529    39.3
182530    39.3
182531    33.9
182532    33.9
182533    33.9
182534    33.9
182535    33.9
182536    33.9
182537    23.0
182538    23.0
182539    23.0
182540    23.0
182541    23.0
182542    23.0
182543    50.1
182544    50.1
182545    50.1
182546    50.1
182547    50.1
182548    50.1
Name: Yield, Length: 359427, dtype: float64


In [11]:
# Importing the library for splitting the data into Training and Testring sets
from sklearn.model_selection import train_test_split

In [12]:
# Splitting data to Train set and Test set
y = total_data2['Yield']
X = total_data2.drop(['Yield'],axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
# Scaling the values

from sklearn import preprocessing
columns_to_scale = total_data2.columns.tolist()
columns_to_scale = [x for x in columns_to_scale if x != 'Yield']
print(columns_to_scale)

std_scaler = preprocessing.StandardScaler().fit(X_train[columns_to_scale])
minmax_scaler = preprocessing.MinMaxScaler().fit(X_train[columns_to_scale])

X_train[columns_to_scale] = std_scaler.transform(X_train[columns_to_scale])

X_test[columns_to_scale] = std_scaler.transform(X_test[columns_to_scale])



['apparentTemperatureMax', 'apparentTemperatureMin', 'cloudCover', 'dewPoint', 'humidity', 'precipIntensity', 'precipIntensityMax', 'precipProbability', 'precipAccumulation', 'precipTypeIsRain', 'precipTypeIsSnow', 'precipTypeIsOther', 'pressure', 'temperatureMax', 'temperatureMin', 'visibility', 'windBearing', 'windSpeed', 'NDVI', 'DayInSeason']


D:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  # This is added back by InteractiveShellApp.init_path()
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by Interactiv

In [14]:
# Converting the features to float data type
X.astype(float),y.astype(float)

(        apparentTemperatureMax  apparentTemperatureMin  cloudCover  dewPoint  \
 0                        35.70                   20.85        0.00     29.53   
 1                        35.10                   26.92        0.00     29.77   
 2                        33.38                   26.95        0.00     29.36   
 3                        28.05                   25.93        0.91     29.47   
 4                        28.83                   25.98        0.91     29.86   
 5                        30.32                   22.40        0.00     28.91   
 6                        61.87                   24.98        0.00     33.35   
 7                        61.94                   24.74        0.00     33.20   
 8                        61.19                   26.95        0.00     35.18   
 9                        61.35                   26.87        0.00     35.15   
 10                       61.17                   27.18        0.00     35.47   
 11                       60

### Preprocessing End

# Polynomial Regression

In [15]:

# Fitting Linear Regression to the dataset
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression(normalize=True)
lin_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [16]:
# Fitting Polynomial Regression to the dataset
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 3)
X_poly = poly_reg.fit_transform(X)
poly_reg.fit(X_poly, y)
lin_reg_2 = LinearRegression(normalize=True)
lin_reg_2.fit(X_poly, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [17]:
y_predPR = lin_reg_2.predict(X_poly)

In [18]:
#print(lin_reg_2.score(X_train,y_train))
print(lin_reg_2.score(X_poly,y))
print(r2_score(y,y_predPR))

0.3724026576931827
0.3724026576931827


#### Polynomial Regression end

# Decision Tree Regression

In [19]:
from sklearn.tree import DecisionTreeRegressor

In [20]:
dtregressor = DecisionTreeRegressor(max_depth=None, min_samples_split=2, random_state=42)
dtregressor.fit(X_train, y_train)

y_predDT = dtregressor.predict(X_test)

In [21]:
print(y_predDT)

[12.7 49.3 51.2 ...  9.6 27.7 45.6]


In [22]:
print(dtregressor.score(X_test,y_test))
print(r2_score(y_test,y_predDT))

0.6752373905065269
0.6752373905065269


### Decision Tree end

# Random Forest Regression

In [23]:
# Importing the Library
from sklearn.ensemble import RandomForestRegressor

In [24]:
# instantiating the model
rfregressor = RandomForestRegressor(n_estimators=100, random_state = 42)
model=rfregressor.fit(X_train, y_train)

In [25]:
# Predicting Test Set
y_pred = model.predict(X_test)

In [26]:
# Print predocted values
print(y_pred)

[16.163 38.278 46.064 ... 12.866 28.459 28.988]


In [27]:
# Storing values of predicted Yield in a new column
total_data2['y_pred']=np.NAN
total_data2.iloc[(len(total_data2)-len(y_pred)):,-1:] = y_pred
total_data3 = total_data2.dropna
print(y_pred)

[16.163 38.278 46.064 ... 12.866 28.459 28.988]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
D:\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [28]:
# Checking the Accuracy
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.9797202012088836
0.8548137617329514


In [29]:
# important features
imp = list(zip(X,model.feature_importances_))
imp=sorted(imp,key=lambda x:x[1])

In [30]:
# Printing the feature importance
print(imp)

[('precipTypeIsOther', 0.0), ('precipTypeIsSnow', 0.0003020010512853739), ('precipTypeIsRain', 0.001183343697379852), ('precipAccumulation', 0.003853853210302644), ('precipProbability', 0.0068206020273084015), ('precipIntensityMax', 0.012184726118114865), ('precipIntensity', 0.014831802483320708), ('cloudCover', 0.03287244582035734), ('apparentTemperatureMax', 0.04539134270719786), ('temperatureMin', 0.04742161367504414), ('visibility', 0.048403077341477474), ('temperatureMax', 0.06468851166097943), ('apparentTemperatureMin', 0.06719397021696268), ('dewPoint', 0.07028924073801203), ('humidity', 0.07963215466904505), ('windSpeed', 0.08724171371860778), ('NDVI', 0.09549803488641294), ('DayInSeason', 0.1008345565765131), ('windBearing', 0.10975762036661407), ('pressure', 0.11159938903506425)]


### random forests end